pipeline {
	agent any
		stages {
			stage('Clean stage') {
				steps {
					dir("MiscDemo") {
						bat 'mvn clean'
					}
				}
			}
			stage('Compile stage') {
				steps {
					dir("MiscDemo") {
						bat 'mvn compile'
					}
				}
			}
			stage('Install stage') {
				steps {
					dir("MiscDemo") {
						bat 'mvn install'
					}
				}
			}
		}
}